"""
A collection of all constants defined in PyGVisuals.
"""

from ..widgets.selection_text_widget import START, END, CURSOR, INSERT, CURRENT, SELECTION
from ..widgets.listbox import VIEWPOINT
from .trueno import TRUENO_REGULAR, TRUENO_REGULAR_ITALIC, TRUENO_BOLD, TRUENO_BOLD_ITALIC, TRUENO_BOLD_OUTLINE, TRUENO_BOLD_OUTLINE_ITALIC, TRUENO_SEMIBOLD, TRUENO_SEMIBOLD_ITALIC, TRUENO_EXTRABOLD, TRUENO_EXTRABOLD_ITALIC, TRUENO_EXTRABOLD_OUTLINE, TRUENO_EXTRABOLD_OUTLINE_ITALIC, TRUENO_BLACK, TRUENO_BLACK_ITALIC, TRUENO_BLACK_OUTLINE, TRUENO_BLACK_OUTLINE_ITALIC, TRUENO_ULTRABLACK, TRUENO_ULTRABLACK_ITALIC, TRUENO_LIGHT, TRUENO_LIGHT_ITALIC, TRUENO_ULTRALIGHT, TRUENO_ULTRALIGHT_ITALIC
