"""
A collection of all constants defined in PyGVisuals.
"""

from ..widgets.selection_text_widget import START, END, CURSOR, INSERT, CURRENT, SELECTION
from ..widgets.listbox import VIEWPOINT
from .trueno import FONT_REGULAR, FONT_REGULAR_ITALIC, FONT_BOLD, FONT_BOLD_ITALIC, FONT_BOLD_OUTLINE, FONT_BOLD_OUTLINE_ITALIC, FONT_SEMIBOLD, FONT_SEMIBOLD_ITALIC, FONT_EXTRABOLD, FONT_EXTRABOLD_ITALIC, FONT_EXTRABOLD_OUTLINE, FONT_EXTRABOLD_OUTLINE_ITALIC, FONT_BLACK, FONT_BLACK_ITALIC, FONT_BLACK_OUTLINE, FONT_BLACK_OUTLINE_ITALIC, FONT_ULTRABLACK, FONT_ULTRABLACK_ITALIC, FONT_LIGHT, FONT_LIGHT_ITALIC, FONT_ULTRALIGHT, FONT_ULTRALIGHT_ITALIC
